PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS FileTags;
DROP TABLE IF EXISTS Tags;
DROP TABLE IF EXISTS Files;

CREATE TABLE IF NOT EXISTS Files (
  FileID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  FilePath TEXT NOT NULL,
  LastIndexed UNSIGNED BIGINT DEFAULT (strftime('%s', 'now')) NOT NULL
);

CREATE UNIQUE INDEX `id_files_filepath` ON `Files` (FilePath ASC);

CREATE TABLE IF NOT EXISTS Tags (
  TagID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  Tag TEXT NOT NULL,
  TagAdded UNSIGNED BIG INT DEFAULT (strftime('%s', 'now')) NOT NULL
);

CREATE UNIQUE INDEX `id_tags_tag` ON Tags (Tag ASC);

CREATE TABLE IF NOT EXISTS FileTags (
  FileTagID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  FileID INT NOT NULL REFERENCES Files(FileID) ON UPDATE CASCADE ON DELETE CASCADE,
  TagID INT NOT NULL REFERENCES Tags(TagID) ON UPDATE CASCADE ON DELETE CASCADE,
  Part UNSIGNED SMALLINT DEFAULT NULL,
  Priority UNSIGNED TINYINT DEFAULT 0,
  Manual BOOL DEFAULT False
);
